export const languages = [
  { name: "Marathi", value: "mr", select: true },
  { name: "Hindi", value: "hi", select: true },
  { name: "English", value: "en" },
  { name: "Telugu", value: "te" },
  { name: "Tamil", value: "ta" },
  { name: "Kannada", value: "kn" },
  { name: "Malayalam", value: "ml" },
  { name: "Bengali", value: "bn" },
  { name: "Gujarati", value: "gu" },
  { name: "Punjabi", value: "pa" },
  { name: "Assamese", value: "as" },
  { name: "Chinese", value: "zh" },
  { name: "Japanese", value: "ja" },
  { name: "Korean", value: "ko" },
];
